version: "3.8"

services:
  backend:
    build:
      context: ./betha-project-back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - rede-docker
    depends_on:
      - db
    restart: on-failure:3

  frontend:
    build:
      context: ./betha-project-front
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - rede-docker
    depends_on:
      - backend

  db:
    image: postgres:16-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - rede-docker
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d

networks:
  rede-docker:
    driver: bridge
